<package format="2">
  <name>auto_tma</name>
  <version>0.1.0</version>
  <description> AutoTMA experiment </description>

  <maintainer email="yuki.asano3206@gmail.com">Yuki Asano</maintainer>
  <author email="yuki.asano3206@gmail.com">Yuki Asano</author>

  <license>BSD 3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>actionlib</depend>
  <depend>actionlib_msgs</depend>
  <depend>message_generation</depend>
  <depend>message_runtime</depend>
  <depend>rosbridge_suite</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>

  <depend>netzsch_instrument_ros1</depend>
  <depend>nextage_nxa_interface</depend>
  <depend>mitsutoyo_instrument_ros1</depend>
  <depend>plc_ros_bridge</depend>

</package>
